"""
timeline_render.py  [--check] [--budget 168]

Renders .specseed/project_management/TIMELINE.md — the SPRINT-level execution
schedule — wholesale from sprints.json + tickets.json. Unlike ROADMAP.md (which
has human-authored phase/epic prose and is only count-bumped in place by
roadmap_render.py), TIMELINE.md is fully DERIVED, so this script regenerates it
in full.

TIMELINE is the tactical/temporal view (sprints in execution order, effort vs
budget, per-ticket completion, ★ = on critical path). ROADMAP stays the
strategic map; sprints never appear there.

Critical-path marks (★CP) come from tickets_analyze.analyze() if importable;
otherwise they're omitted.

Usage:
    python .specseed/scripts/timeline_render.py
    python .specseed/scripts/timeline_render.py --check   # exit 1 if drift, no write

Exit: 0 OK (or --check no drift), 1 (--check found drift), 2 missing input.
"""

import argparse
import json
import sys
from pathlib import Path


def critical_path_set(tickets):
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import tickets_analyze
        slim = {tid: {"effort_hours": t.get("effort_hours", 0) or 0,
                      "depends_on": t.get("depends_on", []) or [],
                      "status": t.get("status", "todo")}
                for tid, t in tickets.items()}
        return set(tickets_analyze.analyze(slim).get("critical_path", []))
    except Exception:
        return set()


def fmt_hours(h):
    if isinstance(h, float) and h.is_integer():
        h = int(h)
    return f"{h}h"


def render(sprints, tickets, budget):
    cp = critical_path_set(tickets)
    lines = ["# Timeline", "",
             f"Sprints in execution order. Soft budget ~{fmt_hours(budget)}/sprint. "
             f"★ = on critical path.",
             "Tactical schedule — NOT the strategic map (see ROADMAP.md). "
             "Generated by timeline_render.py; do not hand-edit.", ""]

    assigned = set()
    ordered = sorted(sprints.items(), key=lambda kv: (kv[1].get("order", 0), kv[0]))
    for sid, s in ordered:
        status = s.get("status", "planned")
        title = s.get("title", "")
        eff = s.get("effort_hours", 0) or 0
        dates = ""
        if s.get("starts") or s.get("ends"):
            dates = f"  ·  {s.get('starts') or '?'} → {s.get('ends') or '?'}"
        head = f"## {sid}"
        if title:
            head += f" — {title}"
        head += f"  ({status})  ·  {fmt_hours(eff)} / ~{fmt_hours(budget)}{dates}"
        lines.append(head)
        members = s.get("tickets", []) or []
        for tid in members:
            assigned.add(tid)
            t = tickets.get(tid, {})
            ttitle = t.get("title", "") if t else ""
            teff = (t.get("effort_hours", 0) or 0) if t else 0
            done = t.get("issues_done", 0) if t else 0
            total = t.get("issues_total", 0) if t else 0
            star = " ★CP" if tid in cp else ""
            miss = "" if t else "  [MISSING in tickets.json]"
            lines.append(f"- {tid} {ttitle} — {fmt_hours(teff)} ({done}/{total}){star}{miss}")
        if not members:
            lines.append("- (no tickets)")
        lines.append("")

    # Unassigned tickets (have no sprint) — backlog. Skip abandoned (wont_do/deprecated).
    backlog = [tid for tid, t in tickets.items()
               if tid not in assigned and t.get("status") not in ("deprecated", "wont_do")]
    if backlog:
        lines.append("## Unassigned (backlog)")
        for tid in sorted(backlog):
            t = tickets[tid]
            star = " ★CP" if tid in cp else ""
            lines.append(f"- {tid} {t.get('title', '')} — "
                         f"{fmt_hours(t.get('effort_hours', 0) or 0)} "
                         f"({t.get('issues_done', 0)}/{t.get('issues_total', 0)}){star}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pm-dir", default=".specseed/project_management")
    p.add_argument("--sprints-path", default=None)
    p.add_argument("--tickets-path", default=None)
    p.add_argument("--out", default=None, help="default: <pm-dir>/TIMELINE.md")
    p.add_argument("--budget", type=float, default=168.0)
    p.add_argument("--check", action="store_true",
                   help="report drift and exit 1 without writing")
    args = p.parse_args()

    pm = Path(args.pm_dir)
    sprints_path = Path(args.sprints_path) if args.sprints_path else pm / "sprints.json"
    tickets_path = Path(args.tickets_path) if args.tickets_path else pm / "tickets.json"
    out_path = Path(args.out) if args.out else pm / "TIMELINE.md"

    if not sprints_path.exists():
        print(f"ERROR: {sprints_path} not found (run sprints_assemble.py)", file=sys.stderr)
        sys.exit(2)
    if not tickets_path.exists():
        print(f"ERROR: {tickets_path} not found (run tickets_assemble.py)", file=sys.stderr)
        sys.exit(2)
    try:
        sprints = json.loads(sprints_path.read_text(encoding="utf-8"))
        tickets = json.loads(tickets_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"ERROR: malformed JSON: {e}", file=sys.stderr)
        sys.exit(2)

    rendered = render(sprints, tickets, args.budget)
    existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None

    if args.check:
        if rendered != existing:
            print("DRIFT: TIMELINE.md is stale", file=sys.stderr)
            sys.exit(1)
        print("OK: TIMELINE.md up to date")
        sys.exit(0)

    if rendered != existing:
        out_path.write_text(rendered, encoding="utf-8")
        print(f"OK: rendered {len(sprints)} sprint(s) → {out_path}")
    else:
        print(f"OK: TIMELINE.md already current")
    sys.exit(0)


if __name__ == "__main__":
    main()
